#!/bin/bash

# ${1}    => Endpoint base URL
# ${2}    => API token
# ${3}    => Release name (optional)
# exit    => 0 if successful
# example => ./tests/wrap_check https://awesome-tenant.instana.io apitoken

readonly input_file=$(mktemp /tmp/input.XXXXXX)

if [ -n "${3}" ]; then
    echo "{
        \"source\": {
            \"endpoint\": \"${1}\",
            \"api_token\": \"${2}\"
        },
        \"release\": {
            \"id\": \"${3}\"
        }
    }" > "${input_file}"
else
    echo "{
        \"source\": {
            \"endpoint\": \"${1}\",
            \"api_token\": \"${2}\"
        }
    }" > "${input_file}"
fi

docker run -i instana/pipeline-feedback-resource:latest bash -x /opt/resource/check < "${input_file}"