#!/bin/bash

# ${1}    => Endpoint base URL
# ${2}    => API token
# ${3}    => Resource for input
# ${4}    => Release id
# exit    => 0 if successful
# example => ./tests/wrap_in https://awesome-tenant.instana.io apitoken /tmp/$RANDOM release_id_from_check

readonly input_file=$(mktemp /tmp/input.XXXXXX)

echo "Using input file ${input_file}"

if [ -n "${4}" ]; then
    echo "{
        \"source\": {
            \"endpoint\": \"${1}\",
            \"api_token\": \"${2}\"
        },
        \"version\": {
            \"release\": \"${4}\"
        }
    }" > "${input_file}"
else
    echo "{
        \"source\": {
            \"endpoint\": \"${1}\",
            \"api_token\": \"${2}\"
        }
    }" > "${input_file}"
fi

docker run -i instana/pipeline-feedback-resource:latest bash -x /opt/resource/in "${3}" < "${input_file}"