#!/bin/bash

if [ -n "${3}" ]; then
    release_name_file=$(mktemp /tmp/release_name.XXXXXX)
    echo "${3}" > "${release_name_file}"
fi

if [ -n "${4}" ]; then
    start_file=$(mktemp /tmp/start.XXXXXX)
    echo "${4}" > "${start_file}"
fi

if [ -n "${release_name_file}" ]; then
    if [ -n "${start_file}" ]; then
        params="{
            \"release_name_file\": \"${release_name_file}\",
            \"start_file\": \"${start_file}\"
        }"
    else
        params="{
            \"release_name_file\": \"${release_name_file}\"
        }"
    fi
else
    if [ -n "${start_file}" ]; then
        params="{
            \"start_file\": \"${start_file}\"
        }"
    else
        params="{}"
    fi
fi

echo "{
    \"source\": {
        \"endpoint\": \"${1}\",
        \"api_token\": \"${2}\"
    },
    \"params\": ${params}
}" | docker run -i \
        --env='BUILD_PIPELINE_NAME=test_pipeline' \
        --env='BUILD_NAME=test_build' \
        --env='BUILD_ID=42' \
        instana/pipeline-feedback-resource:latest \
        bash -x /opt/resource/out