name: Build and publish image to IBM Cloud Container Registry
on:
  release:
    types: [published]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out release
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to IBM Cloud Container Registry
        uses: docker/login-action@v1 
        with:
          registry: icr.io
          username: ${{ secrets.ICR_USERNAME }}
          password: ${{ secrets.ICR_TOKEN }}
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          build-args: |
            version=${{ github.event.release.tag_name }}
          push: true
          tags: instana/pipeline-feedback-resource
      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}